- hosts: all
  vars_files:
    - 'vars/vault.yml'
  roles:
    - bootstrap
    - nebula

- hosts:
    - sl2
    - shitlist
  vars_files:
    - 'vars/vault.yml'
  roles:
    - traefik

- hosts:
    - dirt
    - shitlist
    - sl2
  vars_files:
    - 'vars/vault.yml'
  roles:
    - role: geerlingguy.docker
      become: true
      vars:
        docker_install_compose: "{{ ansible_os_family == 'Debian' }}"
        docker_package: "{{ 'docker-ce' if ansible_os_family == 'Debian' else 'docker' }}"
        docker_users:
          - "{{ user }}"
      when: 'ansible_architecture|string == "x86_64"'
    - role: geerlingguy.docker_arm
      become: true
      vars:
        docker_install_compose: true
        docker_version: 5:20.10.8~3-0~ubuntu-focal
        docker_users:
          - "{{ user }}"
      when: 'ansible_architecture|string == "aarch64"'     
    - role: docker
      tags: compose
    - role: bwhouse.ansible-role-docker-compose-generator
      become: true
      tags: compose