version: "3.3"
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.7.1
    container_name: uptime-kuma
    volumes:
      - "{{ docker_appdata_dir }}/uptime-kuma:/app/data"
    ports:
      - 3001:3001

  caddy:
    image: caddy:2.4.5
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "{{ docker_appdata_dir }}/caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "{{ docker_appdata_dir }}/caddy/data:/data"
      - "{{ docker_appdata_dir }}/caddy/config:/config"