version: "3.3"
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.7.1
    container_name: uptime-kuma
    volumes:
      - "{{ docker_appdata_dir }}/uptime-kuma:/app/data"
    ports:
      - 3001:3001

#