docker_user:
  id: 3000
  name: dockeruser

docker_compose_file_mask: 0664
docker_compose_directory_mask: 0775

docker_appdata_dir: /opt/appdata

docker_start_command: docker-compose up -d
docker_update_command: docker-compose pull && docker-compose down --remove-orphans && docker-compose rm && docker-compose up -d