nebula_is_lighthouse: false

nebula_outbound_firewall_rules: |
  - port: any
    proto: any
    host: any
nebula_inbound_firewall_rules: |
  - port: any
    proto: icmp
    host: any
  - port: ssh
    proto: tcp
    groups:
      - servers
      - admins
  - port: 443
    proto: tcp
    host: any
  - port: 80
    proto: tcp
    host: any