entryPoints:
    web:
        address: :80
        http:
          redirections:
            entryPoint:
              to: https
              scheme: https
    https:
        address: :443
        http:
          tls:
            certresolver: cloudflare
          #- --entrypoints.https.http.tls.certresolver=dns-cloudflare
    traefik:
        address: ":8080"

providers:
    docker:
        endpoint: unix:///var/run/docker.sock
        watch: true
        exposedByDefault: false
   # file:
   #     filename: /etc/traefik/rules.yaml

api:
  dashboard: true
  insecure: true

certificatesResolvers:
    cloudflare:
        acme:
            email: {{ cloudflare_email }}
            storage: /etc/traefik/acme.json
            dnsChallenge:
                provider: cloudflare
                delayBeforeCheck: 0
                resolvers:
                - 1.1.1.1:53
                - 1.0.0.1:53

serversTransport:
  insecureSkipVerify: true