- name: Create docker group
  group:
    name: "{{ docker_user.name }}"
    state: present
    gid: "{{ docker_user.id }}"
  become: true

- name: Create docker user
  user:
    name: "{{ docker_user.name }}"
    uid: "{{ docker_user.id }}"
    group: "{{ docker_user.name }}"
    create_home: false
  become: true

- name: Add user to docker user group
  user:
    name: "{{ user }}"
    groups: "{{ docker_user.name }}"
    append: true
  become: true

- name: Add user to docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: true
  become: true
  register: add_group

- name: reset ssh connection to allow user changes to affect 'current login user'
  meta: reset_connection
  when: add_group|changed

- name: Clean up docker containers
  cron:
    name: clean up docker containers
    hour: 12
    minute: 0
    weekday: 3
    job: docker system prune -af --volumes

- name: Create docker compose directory
  file:
    path: "{{ docker_appdata_dir }}"
    state: directory
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

